name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Set Google Cloud Project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy Game Server Service
        run: |
          gcloud run deploy team11-game-server-service-from-github-action \
            --port 8080 \
            --source . \
            --allow-unauthenticated \
            --region ${{ vars.GCP_REGION }}
